Repository OrcaCollective/OpenOversight, pull requests merged in 2022-01, with the labels that each got.

#102 Make emails case-insensitive for user operations
  OpenOversight/app/auth/forms.py
  OpenOversight/app/auth/views.py
  OpenOversight/app/commands.py
  OpenOversight/app/main/views.py
  OpenOversight/app/models.py
  OpenOversight/tests/routes/test_auth.py
  OpenOversight/tests/routes/test_other.py
Labels: backend

#89 Generalize data mungers, add roster update script
  .github/workflows/pull_request.yml
  data-munging/assignments.py
  data-munging/common.py
  data-munging/demographic_data.py
  data-munging/divest_spd_links.py
  data-munging/first_employed_date.py
  data-munging/integrate_latest_roster.py
  data-munging/spd_2020_salary_data.py
  data-munging/spd_2021_salary_data.py
Labels: data munge

#99 Munger: OPA Incidents, improved detail formatting
  .github/workflows/pull_request.yml
  OpenOversight/app/main/forms.py
  OpenOversight/app/static/js/incidentDescription.js
  OpenOversight/app/templates/incident_detail.html
  OpenOversight/app/templates/list_officer.html
  OpenOversight/app/templates/officer.html
  OpenOversight/app/templates/partials/incident_fields.html
  OpenOversight/app/templates/partials/links_and_videos_row.html
  OpenOversight/app/templates/partials/officer_descriptions.html
  OpenOversight/app/templates/partials/officer_general_information.html
  OpenOversight/app/templates/partials/officer_incidents.html
  OpenOversight/app/templates/partials/officer_notes.html
  OpenOversight/tests/conftest.py
  OpenOversight/tests/description_overflow.txt
  OpenOversight/tests/routes/test_incidents.py
  OpenOversight/tests/test_functional.py
  data-munging/opa_incidents.py
  justfile
Labels: frontend, data munge

#108 Make incomplete salary more generic, since it's past 2021 now
  OpenOversight/app/templates/partials/officer_salary.html
Labels: frontend

#109 Move links section to after incidents
  OpenOversight/app/templates/officer.html
Labels: frontend

#110 Improve cutoff for incident descriptions
  OpenOversight/app/static/js/incidentDescription.js
  OpenOversight/app/templates/partials/incident_fields.html
  OpenOversight/app/templates/partials/officer_incidents.html
  OpenOversight/tests/test_functional.py
Labels: frontend

#111 Add extra info for upload
  OpenOversight/app/templates/submit_image.html
Labels: frontend

#112 Sort incidents by date descending on officer page
  OpenOversight/app/templates/partials/officer_incidents.html
Labels: backend

#114 Determine assignments based on deltas rather than dropping dupes
  data-munging/assignments.py
Labels: bug, data munge

#115 Change link title name
  data-munging/opa_incidents.py
Labels: data munge
